### ISSUE TITLE
Inifinite loop when calling an Async Future method from a Scheduled method

### ISSUE THREAD

**Issue by fullerlee** [skuzzle/guice-async-extension#1]
I'm trying to parallelise a periodic task by having a scheduled method call an async method, returning a future so that I can join all the threads before existing the scheduled method.
It seems to be going into an infinite loop so running out of memory.  It could well be user error...

```
@Scheduled
@SimpleTrigger(value = 2, initialDelay = 1, timeUnit = TimeUnit.MINUTES, scheduleType = SimpleScheduleType.AT_FIXED_RATE)
public void doScheduledStuff() {
	List<Future<Boolean>> futureResponses = new ArrayList<Future<Boolean>>();
	for (int i = 0 ; i < 1 ; i++) {
		logger.debug("Kicking off async thread: " + i);
		try {
			futureResponses.add(doAsyncThing(""));
		}
		catch (Throwable e) {
			logger.error("Throwable starting thread...");
		}
	}

	for (Future<Boolean> future: futureResponses) {
		try {
			Boolean b = future.get();
				
			logger.debug("response: " + b);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ExecutionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
			
	}
}

@Async
public Future<Boolean> doAsyncThing(String asyncTag) {
	try {
		Thread.sleep(10000);
	} catch (InterruptedException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	return Futures.delegate(true);
}
```

With the error being:
```
Exception in thread "guice-async-0" java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException:
```

**Comment by skuzzle** [comment]
Hi,

using the given code I was not able to reproduce the bug on my system. I've adjusted the first loop to create 100 calls to doAsyncThing and also adjusted minutes to seconds. 

The default configuration uses a cached thread pool for executing the `@Async` methods. That means that the pool will create new Threads on demand if none of the previously created threads ran out of work in the mean time. You might want to try a pool with a fixed number of threads instead:

Within your module:
```java

    @Provides
    @Named("myExecutor")
    ExecutorService myExecutor() {
        return Executors.newFixedThreadPool(4);
    }
```

Then modify your async method accordingly:

```
        @Async
        @Named("myExecutor")
        public Future<Boolean> doAsyncThing(String asyncTag) {
            try {
                Thread.sleep(10000);
            } catch (final InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
            return Futures.delegate(true);
        }
```

Although I'm not completely sure, it might be a good idea to not put the async method into the same class as the scheduled method.
